-- Seguridad (roles y usuarios) y catálogo de productos.
-- Reglas: R-11 (GTIN normalizado a 14 dígitos), R-12 (conversiones), R-13, R-20 (clase ABC), R-23 (UNECE Rec. 20), R-25.

CREATE TABLE role (
    code        varchar(20)  PRIMARY KEY,
    name        varchar(60)  NOT NULL,
    description varchar(255)
);

INSERT INTO role (code, name, description) VALUES
    ('ADMIN',      'Administrador', 'Gestiona usuarios, catálogos y configuración'),
    ('SUPERVISOR', 'Supervisor',    'Registra ajustes y aprueba conteos cíclicos'),
    ('OPERATOR',   'Operador',      'Registra ingresos, egresos, transferencias y conteos en sus bodegas'),
    ('AUDITOR',    'Auditor',       'Solo lectura: kárdex, reportes y bitácora de auditoría');

CREATE TABLE app_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(254) NOT NULL,
    full_name     varchar(120) NOT NULL,
    password_hash varchar(100) NOT NULL,
    role_code     varchar(20)  NOT NULL REFERENCES role (code),
    active        boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    version       bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_email_lower CHECK (email = lower(email))
);

CREATE TABLE category (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   varchar(20) NOT NULL,
    name   varchar(80) NOT NULL,
    active boolean     NOT NULL DEFAULT true,
    CONSTRAINT uk_category_code UNIQUE (code),
    CONSTRAINT ck_category_code CHECK (code ~ '^[A-Z0-9_-]{2,20}$')
);

CREATE TABLE unit_of_measure (
    code varchar(3)  PRIMARY KEY,
    name varchar(40) NOT NULL
);

-- Códigos UNECE Rec. 20 (MLT y XBX: supuesto S-03)
INSERT INTO unit_of_measure (code, name) VALUES
    ('H87', 'Pieza'),
    ('C62', 'Unidad'),
    ('KGM', 'Kilogramo'),
    ('GRM', 'Gramo'),
    ('LTR', 'Litro'),
    ('MLT', 'Mililitro'),
    ('DZN', 'Docena'),
    ('XBX', 'Caja');

CREATE TABLE product (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            varchar(40)  NOT NULL,
    gtin           varchar(14),
    name           varchar(150) NOT NULL,
    description    varchar(500),
    category_id    bigint       NOT NULL REFERENCES category (id),
    base_uom_code  varchar(3)   NOT NULL REFERENCES unit_of_measure (code),
    lot_controlled boolean      NOT NULL DEFAULT false,
    abc_class      varchar(1)   NOT NULL DEFAULT 'C',
    active         boolean      NOT NULL DEFAULT true,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    version        bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uk_product_sku UNIQUE (sku),
    CONSTRAINT uk_product_gtin UNIQUE (gtin),
    CONSTRAINT ck_product_sku CHECK (sku ~ '^[A-Z0-9][A-Z0-9._-]{1,39}$'),
    CONSTRAINT ck_product_gtin CHECK (gtin IS NULL OR gtin ~ '^[0-9]{14}$'),
    CONSTRAINT ck_product_abc CHECK (abc_class IN ('A', 'B', 'C'))
);

CREATE INDEX ix_product_category ON product (category_id);
CREATE INDEX ix_product_name ON product (lower(name));

CREATE TABLE product_uom_conversion (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint        NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    uom_code   varchar(3)    NOT NULL REFERENCES unit_of_measure (code),
    factor     numeric(18,6) NOT NULL,
    gtin       varchar(14),
    CONSTRAINT uk_conversion_product_uom UNIQUE (product_id, uom_code),
    CONSTRAINT uk_conversion_gtin UNIQUE (gtin),
    CONSTRAINT ck_conversion_factor CHECK (factor > 0),
    CONSTRAINT ck_conversion_gtin CHECK (gtin IS NULL OR gtin ~ '^[0-9]{14}$')
);
