-- Almacenaje: bodegas, ubicaciones, lotes, stock y mínimos.
-- Reglas: R-07 (stock nunca negativo), R-10 (@Version), R-13 (lote AI 10), R-17 (bodega → pasillo → estante → nivel), R-19, R-25.

CREATE TABLE warehouse (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       varchar(10)  NOT NULL,
    name       varchar(100) NOT NULL,
    city       varchar(60),
    address    varchar(200),
    active     boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL DEFAULT now(),
    version    bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uk_warehouse_code UNIQUE (code),
    CONSTRAINT ck_warehouse_code CHECK (code ~ '^[A-Z0-9-]{2,10}$')
);

CREATE TABLE user_warehouse (
    user_id      bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    warehouse_id bigint NOT NULL REFERENCES warehouse (id),
    PRIMARY KEY (user_id, warehouse_id)
);

CREATE TABLE location (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id bigint      NOT NULL REFERENCES warehouse (id),
    code         varchar(20) NOT NULL,
    aisle        varchar(3)  NOT NULL,
    rack         varchar(3)  NOT NULL,
    level        varchar(3)  NOT NULL,
    type         varchar(12) NOT NULL DEFAULT 'STORAGE',
    active       boolean     NOT NULL DEFAULT true,
    version      bigint      NOT NULL DEFAULT 0,
    CONSTRAINT uk_location_code UNIQUE (warehouse_id, code),
    CONSTRAINT uk_location_id_warehouse UNIQUE (id, warehouse_id),
    CONSTRAINT ck_location_parts CHECK (aisle ~ '^[A-Z0-9]{1,3}$' AND rack ~ '^[A-Z0-9]{1,3}$' AND level ~ '^[A-Z0-9]{1,3}$'),
    CONSTRAINT ck_location_type CHECK (type IN ('RECEIVING', 'STORAGE', 'SHIPPING', 'QUARANTINE'))
);

CREATE TABLE lot (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      bigint      NOT NULL REFERENCES product (id),
    lot_number      varchar(20) NOT NULL,
    expiry_date     date,
    production_date date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_lot_product_number UNIQUE (product_id, lot_number),
    CONSTRAINT uk_lot_id_product UNIQUE (id, product_id),
    CONSTRAINT ck_lot_number CHECK (lot_number ~ '^[A-Za-z0-9._/-]{1,20}$'),
    CONSTRAINT ck_lot_dates CHECK (production_date IS NULL OR expiry_date IS NULL OR production_date <= expiry_date)
);

CREATE INDEX ix_lot_expiry ON lot (expiry_date);

CREATE TABLE stock (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   bigint        NOT NULL REFERENCES product (id),
    warehouse_id bigint        NOT NULL,
    location_id  bigint        NOT NULL,
    lot_id       bigint,
    quantity     numeric(18,4) NOT NULL DEFAULT 0,
    version      bigint        NOT NULL DEFAULT 0,
    updated_at   timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT fk_stock_location FOREIGN KEY (location_id, warehouse_id) REFERENCES location (id, warehouse_id),
    CONSTRAINT fk_stock_lot FOREIGN KEY (lot_id, product_id) REFERENCES lot (id, product_id),
    CONSTRAINT uk_stock_position UNIQUE NULLS NOT DISTINCT (product_id, location_id, lot_id),
    CONSTRAINT ck_stock_non_negative CHECK (quantity >= 0)
);

CREATE INDEX ix_stock_product_warehouse ON stock (product_id, warehouse_id);
CREATE INDEX ix_stock_warehouse ON stock (warehouse_id);

CREATE TABLE stock_min_rule (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   bigint        NOT NULL REFERENCES product (id),
    warehouse_id bigint        NOT NULL REFERENCES warehouse (id),
    min_quantity numeric(18,4) NOT NULL,
    CONSTRAINT uk_stock_min_rule UNIQUE (product_id, warehouse_id),
    CONSTRAINT ck_stock_min_rule CHECK (min_quantity >= 0)
);
