-- Operación: costo promedio por producto, movimientos y kárdex.
-- Reglas: R-01..R-04 (costo promedio NIC 2), R-06 (kárdex inmutable), R-08 (transferencia), R-10, R-22 (documento de referencia).

CREATE TABLE product_cost (
    product_id       bigint        PRIMARY KEY REFERENCES product (id),
    quantity_on_hand numeric(18,4) NOT NULL DEFAULT 0,
    total_value      numeric(20,4) NOT NULL DEFAULT 0,
    average_cost     numeric(20,6) NOT NULL DEFAULT 0,
    last_movement_at timestamptz,
    version          bigint        NOT NULL DEFAULT 0,
    CONSTRAINT ck_product_cost_values CHECK (quantity_on_hand >= 0 AND total_value >= 0 AND average_cost >= 0)
);

CREATE TABLE document_type (
    code   varchar(4)  PRIMARY KEY,
    name   varchar(80) NOT NULL,
    source varchar(8)  NOT NULL,
    CONSTRAINT ck_document_type_source CHECK (source IN ('SRI', 'INTERNAL'))
);

-- Tipos de comprobante del SRI (ficha técnica de comprobantes electrónicos) + documentos internos
INSERT INTO document_type (code, name, source) VALUES
    ('01',  'Factura',                     'SRI'),
    ('03',  'Liquidación de compra',       'SRI'),
    ('04',  'Nota de crédito',             'SRI'),
    ('05',  'Nota de débito',              'SRI'),
    ('06',  'Guía de remisión',            'SRI'),
    ('OC',  'Orden de compra',             'INTERNAL'),
    ('PED', 'Pedido de despacho',          'INTERNAL'),
    ('OT',  'Orden de transferencia',      'INTERNAL'),
    ('AJ',  'Acta de ajuste',              'INTERNAL'),
    ('CC',  'Conteo cíclico',              'INTERNAL'),
    ('SI',  'Saldo inicial',               'INTERNAL');

CREATE SEQUENCE movement_number_seq;

CREATE TABLE inventory_movement (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number              varchar(20)  NOT NULL,
    type                varchar(12)  NOT NULL,
    warehouse_id        bigint       NOT NULL REFERENCES warehouse (id),
    target_warehouse_id bigint       REFERENCES warehouse (id),
    reference_type_code varchar(4)   NOT NULL REFERENCES document_type (code),
    reference_number    varchar(40)  NOT NULL,
    reason              varchar(255),
    occurred_at         timestamptz  NOT NULL,
    created_by_id       bigint       NOT NULL REFERENCES app_user (id),
    cycle_count_id      bigint,
    CONSTRAINT uk_movement_number UNIQUE (number),
    CONSTRAINT ck_movement_type CHECK (type IN ('RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT')),
    CONSTRAINT ck_movement_target CHECK ((type = 'TRANSFER') = (target_warehouse_id IS NOT NULL))
);

CREATE INDEX ix_movement_occurred ON inventory_movement (occurred_at DESC);
CREATE INDEX ix_movement_warehouse ON inventory_movement (warehouse_id);

CREATE TABLE movement_line (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id                bigint        NOT NULL REFERENCES inventory_movement (id),
    line_no                    smallint      NOT NULL,
    product_id                 bigint        NOT NULL REFERENCES product (id),
    warehouse_id               bigint        NOT NULL,
    location_id                bigint        NOT NULL,
    lot_id                     bigint,
    direction                  varchar(3)    NOT NULL,
    quantity                   numeric(18,4) NOT NULL,
    uom_code                   varchar(3)    NOT NULL REFERENCES unit_of_measure (code),
    uom_quantity               numeric(18,4) NOT NULL,
    unit_cost                  numeric(20,6) NOT NULL,
    total_cost                 numeric(20,4) NOT NULL,
    balance_quantity           numeric(18,4) NOT NULL,
    balance_value              numeric(20,4) NOT NULL,
    average_cost               numeric(20,6) NOT NULL,
    warehouse_balance_quantity numeric(18,4) NOT NULL,
    occurred_at                timestamptz   NOT NULL,
    CONSTRAINT fk_line_location FOREIGN KEY (location_id, warehouse_id) REFERENCES location (id, warehouse_id),
    CONSTRAINT fk_line_lot FOREIGN KEY (lot_id, product_id) REFERENCES lot (id, product_id),
    CONSTRAINT uk_line_movement_no UNIQUE (movement_id, line_no),
    CONSTRAINT ck_line_direction CHECK (direction IN ('IN', 'OUT')),
    CONSTRAINT ck_line_quantities CHECK (quantity > 0 AND uom_quantity > 0),
    CONSTRAINT ck_line_costs CHECK (unit_cost >= 0 AND total_cost >= 0 AND average_cost >= 0),
    CONSTRAINT ck_line_balances CHECK (balance_quantity >= 0 AND balance_value >= 0 AND warehouse_balance_quantity >= 0)
);

CREATE INDEX ix_line_kardex ON movement_line (product_id, id);
CREATE INDEX ix_line_kardex_warehouse ON movement_line (product_id, warehouse_id, id);
CREATE INDEX ix_line_movement ON movement_line (movement_id);

-- R-06: el kárdex es append-only. Las correcciones se hacen con nuevos movimientos.
CREATE FUNCTION forbid_mutation() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'La tabla % es de solo inserción (%)', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER trg_movement_line_append_only
    BEFORE UPDATE OR DELETE ON movement_line
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

CREATE TRIGGER trg_movement_append_only
    BEFORE UPDATE OR DELETE ON inventory_movement
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
