-- Conteo cíclico con aprobación, bitácora de auditoría y vista de conciliación kárdex vs. stock.
-- Reglas: R-09 (conciliación), R-20 (conteo ciego), R-21 (segregación de funciones y auditoría).

CREATE SEQUENCE cycle_count_number_seq;

CREATE TABLE cycle_count (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number                 varchar(20)  NOT NULL,
    warehouse_id           bigint       NOT NULL REFERENCES warehouse (id),
    status                 varchar(12)  NOT NULL DEFAULT 'OPEN',
    aisle_filter           varchar(3),
    abc_filter             varchar(1),
    notes                  varchar(255),
    created_by_id          bigint       NOT NULL REFERENCES app_user (id),
    created_at             timestamptz  NOT NULL DEFAULT now(),
    submitted_by_id        bigint       REFERENCES app_user (id),
    submitted_at           timestamptz,
    reviewed_by_id         bigint       REFERENCES app_user (id),
    reviewed_at            timestamptz,
    review_notes           varchar(500),
    adjustment_movement_id bigint       REFERENCES inventory_movement (id),
    version                bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uk_cycle_count_number UNIQUE (number),
    CONSTRAINT ck_cycle_count_status CHECK (status IN ('OPEN', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_cycle_count_abc CHECK (abc_filter IS NULL OR abc_filter IN ('A', 'B', 'C')),
    -- Segregación de funciones (COSO, principio 10): quien envía el conteo no puede aprobarlo
    CONSTRAINT ck_cycle_count_segregation CHECK (reviewed_by_id IS NULL OR reviewed_by_id <> submitted_by_id),
    CONSTRAINT ck_cycle_count_review CHECK (status NOT IN ('APPROVED', 'REJECTED') OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL))
);

CREATE INDEX ix_cycle_count_warehouse ON cycle_count (warehouse_id, status);

ALTER TABLE inventory_movement
    ADD CONSTRAINT fk_movement_cycle_count FOREIGN KEY (cycle_count_id) REFERENCES cycle_count (id);

CREATE TABLE cycle_count_line (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_count_id   bigint        NOT NULL REFERENCES cycle_count (id),
    location_id      bigint        NOT NULL REFERENCES location (id),
    product_id       bigint        NOT NULL REFERENCES product (id),
    lot_id           bigint        REFERENCES lot (id),
    counted_quantity numeric(18,4),
    system_quantity  numeric(18,4),
    difference       numeric(18,4),
    unit_cost        numeric(20,6),
    counted_by_id    bigint        REFERENCES app_user (id),
    counted_at       timestamptz,
    note             varchar(255),
    version          bigint        NOT NULL DEFAULT 0,
    CONSTRAINT uk_cycle_count_line UNIQUE NULLS NOT DISTINCT (cycle_count_id, location_id, product_id, lot_id),
    CONSTRAINT ck_cycle_count_line_counted CHECK (counted_quantity IS NULL OR counted_quantity >= 0),
    CONSTRAINT ck_cycle_count_line_consistency CHECK (
        (counted_quantity IS NULL AND difference IS NULL) OR
        (counted_quantity IS NOT NULL AND system_quantity IS NOT NULL AND difference = counted_quantity - system_quantity)
    )
);

CREATE INDEX ix_cycle_count_line_count ON cycle_count_line (cycle_count_id);

CREATE TABLE audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at timestamptz  NOT NULL DEFAULT now(),
    actor_email varchar(254) NOT NULL,
    action      varchar(40)  NOT NULL,
    entity_type varchar(40)  NOT NULL,
    entity_id   varchar(40),
    details     jsonb
);

CREATE INDEX ix_audit_log_occurred ON audit_log (occurred_at DESC);
CREATE INDEX ix_audit_log_entity ON audit_log (entity_type, entity_id);

CREATE TRIGGER trg_audit_log_append_only
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION forbid_mutation();

-- R-09: el kárdex cuadra con el stock. Una fila por producto con las cinco cifras que deben coincidir.
CREATE VIEW v_stock_reconciliation AS
SELECT p.id                                   AS product_id,
       p.sku                                  AS sku,
       p.name                                 AS product_name,
       coalesce(s.stock_quantity, 0)          AS stock_quantity,
       coalesce(pc.quantity_on_hand, 0)       AS valuation_quantity,
       coalesce(k.kardex_quantity, 0)         AS kardex_quantity,
       coalesce(last_line.balance_quantity, 0) AS last_balance_quantity,
       coalesce(pc.total_value, 0)            AS valuation_value,
       coalesce(k.kardex_value, 0)            AS kardex_value
FROM product p
LEFT JOIN (SELECT product_id, sum(quantity) AS stock_quantity FROM stock GROUP BY product_id) s
       ON s.product_id = p.id
LEFT JOIN product_cost pc
       ON pc.product_id = p.id
LEFT JOIN (SELECT product_id,
                  sum(CASE WHEN direction = 'IN' THEN quantity ELSE -quantity END)     AS kardex_quantity,
                  sum(CASE WHEN direction = 'IN' THEN total_cost ELSE -total_cost END) AS kardex_value
           FROM movement_line
           GROUP BY product_id) k
       ON k.product_id = p.id
LEFT JOIN LATERAL (SELECT ml.balance_quantity
                   FROM movement_line ml
                   WHERE ml.product_id = p.id
                   ORDER BY ml.id DESC
                   LIMIT 1) last_line ON true;
